version: "3.8"

services:
  app:
    profiles: ["app"]
    restart: always
    container_name: shipping
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PROJECT_PORT}
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    networks:
      - shipping
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "local"

  postgres:
    container_name: postgres-${PROJECT_NAME}
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_ROL=${POSTGRES_ROL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - shipping
    restart: always

  pgadmin:
    container_name: pgadmin-${PROJECT_NAME}
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - shipping
    restart: always

  redis:
    container_name: redis-${PROJECT_NAME}
    image: bitnami/redis:6.2.7
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - shipping
  redis-commander:
    container_name: redis-commander-${PROJECT_NAME}
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis-${PROJECT_NAME}
      REDIS_HOST: redis-${PROJECT_NAME}
      REDIS_PORT: redis:${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - shipping

networks:
  shipping:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis:
  redis-config:
